### ISSUE TITLE
extract_segmentation_features throws TypeError: expected string or buffer

### ISSUE THREAD

**Issue by arne-cl** [EducationalTestingService/rstfinder#41]
I was able to install `discourse-parser` and ran the input preparation steps. I can't get the segmentation to run, though.

``` python
$ /opt/discourse-parsing# extract_segmentation_features rst_discourse_tb_edus_TRAINING_TRAIN.json rst_discourse_tb_edus_features_TRAINING_TRAIN.tsv
Traceback (most recent call last):
  File "/usr/local/bin/extract_segmentation_features", line 9, in <module>
    load_entry_point('discourseparsing==0.2.1', 'console_scripts', 'extract_segmentation_features')()
  File "/usr/local/lib/python3.4/dist-packages/discourseparsing-0.2.1-py3.4.egg/discourseparsing/extract_segmentation_features.py", line 34, in main
  File "/usr/local/lib/python3.4/dist-packages/discourseparsing-0.2.1-py3.4.egg/discourseparsing/discourse_segmentation.py", line 60, in extract_segmentation_features
  File "/usr/local/lib/python3.4/dist-packages/nltk/tree.py", line 609, in fromstring
    for match in token_re.finditer(s):
TypeError: expected string or buffer
```

**Comment by desilinguist** [comment]
Can you try with python 3.3 and see if that makes a difference?

**Comment by aoifecahill** [comment]
I think it could be the version of nltk, it might be too new?

**Comment by arne-cl** [comment]
I was using Python 3.4 with NLTK version 3.0.3.

Now I reinstalled the whole thing with Python 3.3, but that doesn't solve the issue. Which version of NLTK do you recommend?

``` python
/opt/discourse-parsing# extract_segmentation_features rst_discourse_tb_edus_TRAINING_TRAIN.json rst_discourse_tb_edus_features_TRAINING_TRAIN.tsv
Traceback (most recent call last):
  File "/usr/local/bin/extract_segmentation_features", line 9, in <module>
    load_entry_point('discourseparsing==0.2.1', 'console_scripts', 'extract_segmentation_features')()
  File "/usr/local/lib/python3.3/dist-packages/discourseparsing-0.2.1-py3.3.egg/discourseparsing/extract_segmentation_features.py", line 34, in main
  File "/usr/local/lib/python3.3/dist-packages/discourseparsing-0.2.1-py3.3.egg/discourseparsing/discourse_segmentation.py", line 60, in extract_segmentation_features
  File "/usr/local/lib/python3.3/dist-packages/nltk/tree.py", line 609, in fromstring
    for match in token_re.finditer(s):
TypeError: expected string or buffer
```

**Comment by desilinguist** [comment]
Try nltk version 3.0.0

**Comment by arne-cl** [comment]
Thanks, it works now. 

I had to rerun `convert_rst_discourse_tb` and `make_traindev_split.py` before `extract_segmentation_features` would work, so I'm not sure if the problem was caused by the Python or NLTK version difference.
